language: go
os: linux

jobs:
  include:
    - go: "1.13.x"
      env: GO111MODULE=off
    - go: "1.13.x"
      env: GO111MODULE=on
    - go: "1.14.x"
      env: GO111MODULE=off
    - go: "1.14.x"
      env: GO111MODULE=on

script:
  - go test -v -race ./...